import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { provisionTenant } from "@/lib/tenant";
import {
  createSession,
  generateToken,
  setSessionCookie,
  setActiveOrganizationId,
} from "@/lib/auth";
import { slugify } from "@/lib/tenant";

export const runtime = "nodejs";

const COHORT_CAP = 100;
const SLUG_RETRY_LIMIT = 3;

function redirect(req: NextRequest, path: string) {
  // Prefer the public app URL over req.url — behind Railway's reverse proxy
  // req.url is the internal origin (localhost:8080), which breaks redirects.
  const base =
    process.env.NEXT_PUBLIC_APP_URL ??
    (() => {
      const forwardedHost = req.headers.get("x-forwarded-host");
      const forwardedProto = req.headers.get("x-forwarded-proto") ?? "https";
      if (forwardedHost) return `${forwardedProto}://${forwardedHost}`;
      return new URL(req.url).origin;
    })();
  return NextResponse.redirect(new URL(path, base));
}

/**
 * Same-origin path guard: only accept a `/path` that isn't protocol-relative
 * and doesn't contain a scheme. Anything else falls through to the default.
 */
/**
 * Accepts either a same-origin path (starting with `/`) or a full HTTPS URL
 * whose host ends in `.aju.sh` (e.g. `https://mcp.aju.sh/authorize?...`).
 * External hosts are rejected so a malicious `?return_to=...` can't turn
 * magic-link verification into an open redirect.
 */
function safeReturnTo(raw: string | null | undefined): string | null {
  if (!raw) return null;

  if (raw.startsWith("/")) {
    if (raw.startsWith("//")) return null;
    if (raw.startsWith("/\\")) return null;
    if (/^\/[a-z][a-z0-9+.-]*:/i.test(raw)) return null;
    return raw;
  }

  try {
    const parsed = new URL(raw);
    if (parsed.protocol !== "https:") return null;
    const host = parsed.hostname.toLowerCase();
    if (host === "aju.sh" || host.endsWith(".aju.sh")) {
      return parsed.toString();
    }
  } catch {
    // fall through
  }
  return null;
}

/**
 * Matched-org slug validator — a slug generated by `slugify` is already
 * safe, but we re-validate here to avoid trusting raw query params.
 */
function safeMatchedOrg(raw: string | null | undefined): string | null {
  if (!raw || typeof raw !== "string") return null;
  if (!/^[a-z0-9-]{1,64}$/.test(raw)) return null;
  return raw;
}

/**
 * Capitalize the first character of a string (e.g. "alice" → "Alice").
 * Falls back to the raw string if empty.
 */
function capitalize(s: string): string {
  if (!s) return s;
  return s[0].toUpperCase() + s.slice(1);
}

/**
 * 6-char base36 random suffix for slug uniqueness.
 */
function shortId(): string {
  // 36^6 ≈ 2.18B — plenty for collision-retry within a transaction
  let s = "";
  while (s.length < 6) {
    s += Math.random().toString(36).slice(2);
  }
  return s.slice(0, 6);
}

export async function GET(req: NextRequest) {
  const token = req.nextUrl.searchParams.get("token");
  if (!token) return redirect(req, "/?error=missing_token");

  const returnToRaw = req.nextUrl.searchParams.get("return_to");
  const returnTo = safeReturnTo(returnToRaw);
  const matchedOrg = safeMatchedOrg(
    req.nextUrl.searchParams.get("matched_org"),
  );

  // Find + validate the verification row. Don't delete it yet — we want the
  // whole thing to be transactional so nobody can race past the 100 cap.
  const verification = await prisma.verification.findFirst({
    where: { value: token },
  });

  if (!verification) return redirect(req, "/?error=invalid_token");
  if (verification.expiresAt < new Date()) {
    await prisma.verification.delete({ where: { id: verification.id } }).catch(() => {});
    return redirect(req, "/?error=expired_token");
  }

  const email = verification.identifier.toLowerCase();
  const localPart = email.split("@")[0] ?? email;

  // Atomic block: consume token, decide grandfather-vs-waitlist, write user.
  const result = await prisma.$transaction(async (tx) => {
    // Consume the verification row (single-use)
    await tx.verification.delete({ where: { id: verification.id } });

    // If the user already exists, just (re)log them in — don't double-allocate.
    const existing = await tx.user.findUnique({ where: { email } });
    if (existing) {
      return {
        user: existing,
        created: false,
        orgId: existing.personalOrgId,
      };
    }

    const grandfatheredCount = await tx.user.count({
      where: { grandfatheredAt: { not: null } },
    });

    if (grandfatheredCount >= COHORT_CAP) {
      // Cohort closed. Record on waitlist and do NOT create a user account.
      await tx.waitlistEntry.upsert({
        where: { email },
        create: { email, source: "landing" },
        update: {},
      });
      return { waitlisted: true as const };
    }

    // --- Grandfather path: user + personal org + membership + brain ---
    //
    // The chicken-and-egg: User.personalOrgId → Organization.id and
    // Organization.ownerUserId → User.id. Resolve by creating the user
    // with personalOrgId=null first, then creating the org, then
    // back-filling personalOrgId on the user.

    const user = await tx.user.create({
      data: {
        id: generateToken(16),
        email,
        name: localPart,
        emailVerified: true,
        grandfatheredAt: new Date(),
        planTier: "beta_legacy",
      },
    });

    // Slug generation with retry-on-collision. `slugify` already strips
    // anything non-[a-z0-9-], so an empty local-part (shouldn't happen
    // given EMAIL_RE on signup) falls back to "user".
    const baseSlug = slugify(localPart) || "user";
    const orgName = `${capitalize(localPart)} Workspace`;

    let org: { id: string } | null = null;
    let lastErr: unknown = null;
    for (let attempt = 0; attempt < SLUG_RETRY_LIMIT; attempt++) {
      const candidate = `${baseSlug}-${shortId()}`;
      try {
        org = await tx.organization.create({
          data: {
            name: orgName,
            slug: candidate,
            isPersonal: true,
            ownerUserId: user.id,
            planTier: "beta_legacy",
          },
          select: { id: true },
        });
        break;
      } catch (err) {
        lastErr = err;
        // Prisma P2002 → unique constraint violation. Anything else,
        // rethrow immediately — we don't want to silently retry other
        // failures.
        const code = (err as { code?: string } | null)?.code;
        if (code !== "P2002") throw err;
      }
    }
    if (!org) {
      // Exhausted retries on slug collision — extraordinarily unlikely but
      // worth surfacing to the caller rather than swallowing.
      throw lastErr ?? new Error("organization slug allocation failed");
    }

    await tx.user.update({
      where: { id: user.id },
      data: { personalOrgId: org.id },
    });

    await tx.organizationMembership.create({
      data: {
        organizationId: org.id,
        userId: user.id,
        role: "owner",
        acceptedAt: new Date(),
      },
    });

    // NOTE: the starter brain + BrainAccess rows live in the per-tenant DB
    // now, not the control DB. They're created by `provisionTenant` (see
    // seedDefaultBrain), which must run OUTSIDE this transaction because
    // it opens its own connections against the Neon API and the tenant DSN.
    return { user, created: true, orgId: org.id };
  });

  if ("waitlisted" in result && result.waitlisted) {
    // returnTo is intentionally ignored for waitlisted users — the waitlist
    // page is the terminal state for that flow.
    return redirect(req, "/waitlist?email=" + encodeURIComponent(email));
  }

  if ("user" in result && result.user) {
    // If this is the grandfathered-new-user branch, the personal org was
    // created inside the tx above but its per-tenant DB has not yet been
    // provisioned. Provisioning opens its own Neon API + Postgres
    // connections and must run outside the tx. On failure we still sign
    // the user in — the org row exists, so the user can retry provisioning
    // from the settings/onboarding UI rather than being locked out.
    let provisioningError = false;
    if (result.created && result.orgId) {
      try {
        await provisionTenant(result.orgId);
      } catch (err) {
        console.error(
          `[verify] provisionTenant failed for ${result.orgId}:`,
          err,
        );
        provisioningError = true;
      }
    }

    const { token: sessionToken, expiresAt } = await createSession(result.user.id, {
      ipAddress:
        req.headers.get("cf-connecting-ip") ??
        req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ??
        null,
      userAgent: req.headers.get("user-agent"),
    });
    await setSessionCookie(sessionToken, expiresAt);

    // Pin the active org for this session so downstream tenant-scoped
    // reads land on the right workspace without a second round-trip.
    if (result.orgId) {
      await setActiveOrganizationId(result.orgId);
    }

    // Redirect priority:
    //   1. Provisioning failed → onboarding with retry surface
    //   2. Same-origin `return_to` (e.g. post-login deep-link)
    //   3. `matched_org` → team-join prompt
    //   4. Default `/app/onboarding` (puts them inside the dashboard with sidebar visible)
    if (provisioningError) {
      return redirect(req, "/app/onboarding?error=provisioning_failed");
    }
    if (returnTo) return redirect(req, returnTo);
    if (matchedOrg) {
      return redirect(req, `/app/join?org=${encodeURIComponent(matchedOrg)}`);
    }
    return redirect(req, "/app/onboarding");
  }

  return redirect(req, "/?error=unexpected");
}
